# This is a basic workflow to help you get started with Actions

name: Release

on:
  push:
    branches: [main]

  schedule:
    # Runs "at minute 55 past 2" (see https://crontab.guru)
    - cron: "55 2 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hugo setup
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          extended: true
          hugo-version: "0.139.4"
      - run: hugo
      - name: Create pagefind index
        run: npx --yes pagefind@1.3.0 --site public
      - name: Copy atom feed in place
        run: cp public/blog/atom.xml public/atom.xml
      - name: Copy more feeds in place
        run: mkdir public/feed/ && cp public/blog/rss.xml public/feed/index.xml
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: release
          FOLDER: public
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
